WILLER　TRAINS: 京都丹後鉄道
アイジーアールいわて銀河鉄道: IGRいわて銀河鉄道
一般社団法人札幌市交通事業振興公社: 札幌市交通事業振興公社
一般財団法人青函トンネル記念館: 青函トンネル記念館
九州旅客鉄道: JR九州
京都市: 京都市営地下鉄
仙台市: 仙台市営地下鉄
函館市: 函館市電
北海道旅客鉄道: JR北海道
名古屋市: 名古屋市営地下鉄
四国旅客鉄道: JR四国
大阪市高速電気軌道: Osaka Metro
札幌市: 札幌市営地下鉄
東京都: 東京メトロ
東日本旅客鉄道: JR東日本
東海旅客鉄道: JR東海
横浜市: 横浜市営地下鉄
熊本市: 熊本市電
神戸市: 神戸市営地下鉄
福岡市: 福岡市営地下鉄
西日本旅客鉄道: JR西日本
首都圏新都市鉄道: つくばエクスプレス
鹿児島市: 鹿児島市電