source "https://rubygems.org"

ruby "3.3.5"
gem "rails", "~> 7.2.1", ">= 7.2.1.2"

# postgreSQL
gem "pg", "~> 1.1"

# default gem
gem "bootsnap", require: false
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]

# CORS
gem "rack-cors"

# 環境変数管理
gem "config"

# ユーザー認証
gem "devise"

# ユーザーのトークン認証
gem "devise_token_auth"

# 多言語
gem "devise-i18n"

# レスポンスJSONを制御する
gem "active_model_serializers"

group :development, :test do
  gem "factory_bot_rails"
  gem "letter_opener_web"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
