source "https://rubygems.org"

ruby "3.3.5"
gem "rails", "~> 7.2.1", ">= 7.2.1.2"

# postgreSQL
gem "pg", "~> 1.1"

# default gem
gem "bootsnap", require: false
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]

# CORS
gem "rack-cors"

# 環境変数管理
gem "config"

group :development, :test do
  gem "dotenv-rails"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
